// AUTH
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const CHECK_AUTH = 'CHECK_AUTH';
export const AUTH_LOGOUT = 'LOGUT';

// ADVERTISES
export const FETCH_ADS_START = 'FETCH_ADS_START';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
export const FETCH_ADS_FAIL = 'FETCH_ADS_FAIL';

export const REMOVE_AD_SUCCESS = 'REMOVE_AD_SUCCESS';
export const REMOVE_AD_START = 'REMOVE_AD_START';

export const ACCEPT_AD_SUCCESS = 'ACCEPT_AD_SUCCESS';

export const REJECT_AD_SUCCESS = 'REJECT_AD_SUCCESS';

export const FETCH_DETAIL_START = 'FETCH_DETAIL_START';
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';
export const FETCH_DETAIL_FAIL = 'FETCH_DETAIL_FAIL';

// CATEGORIES
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY_START = 'REMOVE_CATEGORY_START';

export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_START = 'EDIT_CATEGORY_START';
